package plugins

import (
	"context"
	"net/http"
)

// Plugin defines the core interface all Wails plugins must implement.
// Every plugin must provide basic metadata and lifecycle management.
type Plugin interface {
	// Metadata methods - required for plugin discovery and management
	Name() string        // Unique identifier for the plugin
	Version() string     // Semver-compatible version string
	Description() string // Human-readable description
	Author() string      // Plugin author information

	// Lifecycle hooks - called by the plugin manager
	Initialize(ctx context.Context, config *PluginConfig) error
	Shutdown(ctx context.Context) error

	// Health check - allows plugin manager to verify plugin status
	Health() error
}

// BuildHook provides hooks into the Wails build process.
// Plugins implementing this interface can modify build behavior.
type BuildHook interface {
	Plugin
	PreBuild(ctx *BuildContext) error  // Called before build starts
	PostBuild(ctx *BuildContext) error // Called after build completes
}

// DevHook provides hooks into the Wails development server.
// Plugins implementing this interface can respond to dev server events.
type DevHook interface {
	Plugin
	PreDev(ctx *DevContext) error  // Called before dev server starts
	PostDev(ctx *DevContext) error // Called after dev server stops
}

// CodeGenerator allows plugins to generate code during build process.
// Useful for creating bindings, type definitions, or other generated files.
type CodeGenerator interface {
	Plugin
	GenerateCode(ctx *GenerationContext) ([]*GeneratedFile, error)
	SupportedLanguages() []string // Languages this generator supports
}

// DevServerExtension allows plugins to extend the development server.
// Plugins can add middleware, routes, or modify server behavior.
type DevServerExtension interface {
	Plugin
	ConfigureDevServer(server DevServerConfigurator) error
	HandleRequest(req *DevRequest) (*DevResponse, error)
}

// FileWatcher allows plugins to watch for file changes.
// Plugins can respond to file system events during development.
type FileWatcher interface {
	Plugin
	GetWatchPaths(projectRoot string) ([]string, error) // Paths to watch
	OnFileChanged(ctx *FileChangeContext) error         // Handle file changes
}

// TemplateProvider allows plugins to provide project templates.
// Plugins can contribute new project types or starter templates.
type TemplateProvider interface {
	Plugin
	GetTemplates() ([]*ProjectTemplate, error)
	InitializeProject(ctx *ProjectInitContext) error
}

// AssetProcessor allows plugins to process frontend assets.
// Plugins can transform, optimize, or bundle frontend resources.
type AssetProcessor interface {
	Plugin
	ProcessAssets(ctx *AssetContext) ([]*ProcessedAsset, error)
	SupportedExtensions() []string // File extensions this processor handles
}

// DevServerConfigurator provides methods for configuring the development server.
type DevServerConfigurator interface {
	AddMiddleware(middleware func(http.Handler) http.Handler)
	AddRoute(pattern string, handler http.HandlerFunc)
	SetStaticDir(path string)
	GetConfig() *DevServerConfig
}

// GeneratedFile represents a file generated by a plugin.
type GeneratedFile struct {
	Path     string // Relative path from project root
	Content  []byte // File content
	Language string // Programming language for syntax highlighting
}

// ProcessedAsset represents an asset processed by a plugin.
type ProcessedAsset struct {
	OriginalPath string            // Original file path
	OutputPath   string            // Where to write the processed file
	Content      []byte            // Processed content
	SourceMap    []byte            // Optional source map
	Metadata     map[string]string // Additional metadata
}

// ProjectTemplate represents a project template provided by a plugin.
type ProjectTemplate struct {
	Name        string            // Template name
	Description string            // Template description
	Language    string            // Primary programming language
	Framework   string            // Frontend framework (if applicable)
	Tags        []string          // Template tags for categorization
	Files       []*TemplateFile   // Template files
	Variables   map[string]string // Template variables
}

// TemplateFile represents a single file in a project template.
type TemplateFile struct {
	Path      string // Relative path from project root
	Content   []byte // File content (may contain template variables)
	Executable bool   // Whether file should be executable
}

// DevRequest represents an HTTP request to the development server.
type DevRequest struct {
	*http.Request
	ProjectRoot string            // Project root directory
	Config      *PluginConfig     // Plugin configuration
	Metadata    map[string]string // Additional request metadata
}

// DevResponse represents an HTTP response from a plugin.
type DevResponse struct {
	StatusCode int                 // HTTP status code
	Headers    map[string]string   // HTTP headers
	Body       []byte              // Response body
	Handled    bool                // Whether plugin handled the request
}

// DevServerConfig contains development server configuration.
type DevServerConfig struct {
	Port      int    // Server port
	Host      string // Server host
	PublicDir string // Public directory for static files
	ProxyURL  string // Proxy URL for API requests
}