package react

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/wailsapp/wails/v2/pkg/plugins"
)

// generateTypes generates TypeScript type definitions
func (p *BasicReactPlugin) generateTypes(services []Service) (*plugins.GeneratedFile, error) {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Generated by Wails basic-react plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	// Generate interfaces for each service
	for _, service := range services {
		if p.config.IncludeComments && service.Doc != "" {
			buf.WriteString(fmt.Sprintf("/**\n * %s\n */\n", service.Doc))
		}

		buf.WriteString(fmt.Sprintf("export interface %sService {\n", service.Name))

		for _, method := range service.Methods {
			if p.config.IncludeComments && method.Doc != "" {
				buf.WriteString(fmt.Sprintf("  /**\n   * %s\n   */\n", method.Doc))
			}

			// Generate method signature
			params := p.formatParams(method.Params)
			returns := p.formatReturns(method.Results)

			buf.WriteString(fmt.Sprintf("  %s(%s): Promise<%s>;\n", 
				lowerFirst(method.Name), params, returns))
		}

		buf.WriteString("}\n\n")
	}

	// Generate window.go declaration
	buf.WriteString("declare global {\n")
	buf.WriteString("  interface Window {\n")
	buf.WriteString("    go: {\n")

	for _, service := range services {
		buf.WriteString(fmt.Sprintf("      %s: %sService;\n", service.Name, service.Name))
	}

	buf.WriteString("    };\n")
	buf.WriteString("  }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export {};\n")

	return &plugins.GeneratedFile{
		Path:      p.config.TypesOutput,
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}, nil
}

// generateHooks generates React hooks for services
func (p *BasicReactPlugin) generateHooks(services []Service) ([]*plugins.GeneratedFile, error) {
	var files []*plugins.GeneratedFile

	hookTemplate := template.Must(template.New("hook").Parse(hookTemplateStr))

	for _, service := range services {
		var buf bytes.Buffer

		// Generate header
		buf.WriteString("// Generated by Wails basic-react plugin\n")
		buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")
		buf.WriteString("import { useState, useCallback } from 'react';\n\n")

		// Generate hooks for each method
		for _, method := range service.Methods {
			data := map[string]interface{}{
				"ServiceName": service.Name,
				"MethodName":  method.Name,
				"HookName":    fmt.Sprintf("use%s", method.Name),
				"Params":      p.formatHookParams(method.Params),
				"ParamNames":  p.formatParamNames(method.Params),
				"ReturnType":  p.formatReturns(method.Results),
			}

			if err := hookTemplate.Execute(&buf, data); err != nil {
				return nil, err
			}

			buf.WriteString("\n")
		}

		filename := fmt.Sprintf("%s/%sHooks.ts", p.config.HooksOutput, service.Name)
		files = append(files, &plugins.GeneratedFile{
			Path:      filename,
			Content:   buf.Bytes(),
			Mode:      0644,
			Overwrite: true,
		})
	}

	return files, nil
}

// generateIndex generates an index file exporting all hooks
func (p *BasicReactPlugin) generateIndex(services []Service) *plugins.GeneratedFile {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Wails basic-react plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	// Export all hooks
	for _, service := range services {
		buf.WriteString(fmt.Sprintf("export * from './%sHooks';\n", service.Name))
	}

	return &plugins.GeneratedFile{
		Path:      fmt.Sprintf("%s/index.ts", p.config.HooksOutput),
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}
}

// formatParams formats method parameters for TypeScript
func (p *BasicReactPlugin) formatParams(params []Param) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		tsType := p.goTypeToTS(param.Type)
		parts = append(parts, fmt.Sprintf("%s: %s", param.Name, tsType))
	}

	return strings.Join(parts, ", ")
}

// formatHookParams formats parameters for React hooks
func (p *BasicReactPlugin) formatHookParams(params []Param) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		tsType := p.goTypeToTS(param.Type)
		parts = append(parts, fmt.Sprintf("%s: %s", param.Name, tsType))
	}

	return strings.Join(parts, ", ")
}

// formatParamNames formats parameter names for function calls
func (p *BasicReactPlugin) formatParamNames(params []Param) string {
	if len(params) == 0 {
		return ""
	}

	var names []string
	for _, param := range params {
		names = append(names, param.Name)
	}

	return strings.Join(names, ", ")
}

// formatReturns formats return types for TypeScript
func (p *BasicReactPlugin) formatReturns(results []Result) string {
	if len(results) == 0 {
		return "void"
	}

	if len(results) == 1 {
		return p.goTypeToTS(results[0].Type)
	}

	// Multiple return values - create a tuple
	var parts []string
	for _, result := range results {
		parts = append(parts, p.goTypeToTS(result.Type))
	}

	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

// goTypeToTS converts Go types to TypeScript types
func (p *BasicReactPlugin) goTypeToTS(goType string) string {
	// Handle common Go types
	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64", 
		 "uint", "uint8", "uint16", "uint32", "uint64",
		 "float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "[]byte":
		return "Uint8Array"
	case "error":
		return "Error"
	case "interface{}":
		return "any"
	}

	// Handle arrays
	if strings.HasPrefix(goType, "[]") {
		elemType := strings.TrimPrefix(goType, "[]")
		return fmt.Sprintf("%s[]", p.goTypeToTS(elemType))
	}

	// Handle pointers
	if strings.HasPrefix(goType, "*") {
		elemType := strings.TrimPrefix(goType, "*")
		return fmt.Sprintf("%s | null", p.goTypeToTS(elemType))
	}

	// Handle maps
	if strings.HasPrefix(goType, "map[") {
		return "Record<string, any>"
	}

	// Handle time.Time
	if strings.Contains(goType, "time.Time") {
		return "Date"
	}

	// Default to any for unknown types
	return "any"
}

// lowerFirst converts first character to lowercase
func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// Hook template
const hookTemplateStr = `export function {{.HookName}}() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const execute = useCallback(async ({{.Params}}) => {
    setLoading(true);
    setError(null);
    
    try {
      const result = await window.go.{{.ServiceName}}.{{.MethodName}}({{.ParamNames}});
      return result;
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      setError(error);
      throw error;
    } finally {
      setLoading(false);
    }
  }, []);
  
  return { execute, loading, error };
}`