package react

// Templates for code generation

// TypeScriptTypeTemplate generates TypeScript interface definitions
const TypeScriptTypeTemplate = `{{range .Services}}
{{if .Doc}}/**
 * {{.Doc}}
 */{{end}}
export interface {{.Name}}Service {
{{range .Methods}}  {{if .Doc}}/**
   * {{.Doc}}
   */{{end}}
  {{.Name | lowerFirst}}({{.Params | formatParams}}): Promise<{{.Results | formatReturns}}>;
{{end}}}
{{end}}

declare global {
  interface Window {
    go: {
{{range .Services}}      {{.Name}}: {{.Name}}Service;
{{end}}    };
  }
}

export {};
`

// ReactHookTemplate generates React hooks for service methods
const ReactHookTemplate = `// Generated by Wails basic-react plugin
// DO NOT EDIT - This file is automatically generated

import { useState, useCallback } from 'react';

{{range .Methods}}
export function use{{.Name}}() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const execute = useCallback(async ({{.Params | formatHookParams}}) => {
    setLoading(true);
    setError(null);
    
    try {
      const result = await window.go.{{$.ServiceName}}.{{.Name}}({{.Params | formatParamNames}});
      return result;
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      setError(error);
      throw error;
    } finally {
      setLoading(false);
    }
  }, []);
  
  return { execute, loading, error };
}
{{end}}
`

// IndexTemplate generates index files for exporting hooks
const IndexTemplate = `// Generated by Wails basic-react plugin
// DO NOT EDIT - This file is automatically generated

{{range .Services}}export * from './{{.Name}}Hooks';
{{end}}
`

// PackageJSONTemplate generates package.json for TypeScript projects
const PackageJSONTemplate = `{
  "name": "{{.ProjectName}}-wails-bindings",
  "version": "1.0.0",
  "description": "Generated TypeScript bindings for {{.ProjectName}}",
  "main": "index.ts",
  "types": "index.ts",
  "scripts": {
    "build": "tsc",
    "dev": "tsc --watch"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "typescript": "^4.9.0"
  },
  "peerDependencies": {
    "react": "^18.0.0"
  }
}
`

// TSConfigTemplate generates tsconfig.json for TypeScript projects
const TSConfigTemplate = `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["DOM", "DOM.Iterable", "ES6"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "declaration": true,
    "declarationMap": true,
    "outDir": "./dist"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
`

// READMETemplate generates README for generated bindings
const READMETemplate = `# {{.ProjectName}} Wails Bindings

This directory contains automatically generated TypeScript bindings and React hooks for your Wails application.

## Generated Files

- \`types/generated.ts\` - TypeScript type definitions for Go services
- \`hooks/generated/\` - React hooks for calling Go methods
- \`hooks/generated/index.ts\` - Barrel export for all hooks

## Usage

### TypeScript Types

\`\`\`typescript
import type { UserServiceService } from './types/generated';

// TypeScript now knows about your Go service methods
\`\`\`

### React Hooks

\`\`\`typescript
import { useGetUser } from './hooks/generated';

function UserProfile({ userId }: { userId: number }) {
  const { execute: getUser, loading, error } = useGetUser();
  const [user, setUser] = useState(null);

  useEffect(() => {
    getUser(userId).then(setUser);
  }, [userId, getUser]);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;
  if (!user) return null;

  return <div>Hello, {user.name}!</div>;
}
\`\`\`

## Configuration

Configure the plugin in your \`wails.json\`:

\`\`\`json
{
  "plugins": {
    "basic-react": {
      "enabled": true,
      "config": {
        "typesOutput": "frontend/src/types/generated.ts",
        "hooksOutput": "frontend/src/hooks/generated",
        "includeComments": true
      }
    }
  }
}
\`\`\`

## Regeneration

To regenerate these files, run:

\`\`\`bash
wails plugin generate
\`\`\`

**Note**: These files are automatically generated. Do not edit them manually as your changes will be lost.
`