package wrf

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/wailsapp/wails/v2/pkg/plugins"
)

// Generator handles code generation for WRF
type Generator struct {
	config *Config
	logger plugins.Logger
}

// NewGenerator creates a new generator instance
func NewGenerator(config *Config, logger plugins.Logger) *Generator {
	return &Generator{
		config: config,
		logger: logger,
	}
}

// GenerateTypes generates TypeScript types with validation
func (g *Generator) GenerateTypes(types []Type) ([]*plugins.GeneratedFile, error) {
	var files []*plugins.GeneratedFile

	// Generate main types file
	typesFile, err := g.generateMainTypesFile(types)
	if err != nil {
		return nil, err
	}
	files = append(files, typesFile)

	return files, nil
}

// GenerateHooks generates React Query hooks
func (g *Generator) GenerateHooks(services []Service) ([]*plugins.GeneratedFile, error) {
	var files []*plugins.GeneratedFile

	for _, service := range services {
		hookFile, err := g.generateServiceHooks(service)
		if err != nil {
			return nil, err
		}
		files = append(files, hookFile)
	}

	return files, nil
}

// GenerateSchemas generates Zod validation schemas
func (g *Generator) GenerateSchemas(types []Type) ([]*plugins.GeneratedFile, error) {
	if g.config.Generation.Types.Validation != "zod" {
		return nil, nil
	}

	var files []*plugins.GeneratedFile

	schemaFile, err := g.generateZodSchemas(types)
	if err != nil {
		return nil, err
	}
	files = append(files, schemaFile)

	return files, nil
}

// GenerateEventTypes generates event type definitions
func (g *Generator) GenerateEventTypes(services []Service) ([]*plugins.GeneratedFile, error) {
	if !g.config.Generation.Events.Typed {
		return nil, nil
	}

	eventFile, err := g.generateEventTypeDefinitions(services)
	if err != nil {
		return nil, err
	}

	return []*plugins.GeneratedFile{eventFile}, nil
}

// GenerateIndexFiles generates index files for exports
func (g *Generator) GenerateIndexFiles(services []Service, types []Type) []*plugins.GeneratedFile {
	var files []*plugins.GeneratedFile

	// Generate hooks index
	hooksIndex := g.generateHooksIndex(services)
	files = append(files, hooksIndex)

	return files
}

// generateMainTypesFile generates the main TypeScript types file
func (g *Generator) generateMainTypesFile(types []Type) (*plugins.GeneratedFile, error) {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("// Generated by Wails WRF plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	// Generate interfaces for each type
	for _, typ := range types {
		if g.config.Generation.Hooks.IncludeComments && typ.Doc != "" {
			buf.WriteString(fmt.Sprintf("/**\n * %s\n */\n", typ.Doc))
		}

		buf.WriteString(fmt.Sprintf("export interface %s {\n", typ.Name))

		for _, field := range typ.Fields {
			if g.config.Generation.Hooks.IncludeComments && field.Doc != "" {
				buf.WriteString(fmt.Sprintf("  /**\n   * %s\n   */\n", field.Doc))
			}

			tsType := g.goTypeToTS(field.Type)
			optional := g.isFieldOptional(field)

			if optional {
				buf.WriteString(fmt.Sprintf("  %s?: %s;\n", g.fieldNameToTS(field.Name), tsType))
			} else {
				buf.WriteString(fmt.Sprintf("  %s: %s;\n", g.fieldNameToTS(field.Name), tsType))
			}
		}

		buf.WriteString("}\n\n")
	}

	// Generate window.go declaration
	buf.WriteString("declare global {\n")
	buf.WriteString("  interface Window {\n")
	buf.WriteString("    go: {\n")
	buf.WriteString("      // Service interfaces will be added by service generation\n")
	buf.WriteString("    };\n")
	buf.WriteString("  }\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export {};\n")

	return &plugins.GeneratedFile{
		Path:      g.config.Generation.Types.Output,
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}, nil
}

// generateServiceHooks generates React Query hooks for a service
func (g *Generator) generateServiceHooks(service Service) (*plugins.GeneratedFile, error) {
	var buf bytes.Buffer

	// Generate header
	buf.WriteString("// Generated by Wails WRF plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	// Import statements based on framework
	switch g.config.Generation.Hooks.Framework {
	case "react-query":
		buf.WriteString("import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';\n")
		buf.WriteString("import { EventsOn, EventsOff } from '@wailsjs/runtime/runtime';\n\n")
	case "swr":
		buf.WriteString("import useSWR, { mutate } from 'swr';\n")
		buf.WriteString("import { EventsOn, EventsOff } from '@wailsjs/runtime/runtime';\n\n")
	default:
		buf.WriteString("import { useState, useCallback, useEffect } from 'react';\n")
		buf.WriteString("import { EventsOn, EventsOff } from '@wailsjs/runtime/runtime';\n\n")
	}

	// Generate hooks for each method
	for _, method := range service.Methods {
		hook, err := g.generateMethodHook(service, method)
		if err != nil {
			return nil, err
		}
		buf.WriteString(hook)
		buf.WriteString("\n\n")
	}

	filename := fmt.Sprintf("%s/%sHooks.ts", g.config.Generation.Hooks.Output, service.Name)
	return &plugins.GeneratedFile{
		Path:      filename,
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}, nil
}

// generateMethodHook generates a hook for a specific method
func (g *Generator) generateMethodHook(service Service, method Method) (string, error) {
	// Determine hook type based on annotations
	queryAnn := ExtractQueryAnnotation(method.Annotations)
	mutationAnn := ExtractMutationAnnotation(method.Annotations)
	subscriptionAnn := ExtractSubscriptionAnnotation(method.Annotations)

	if queryAnn != nil {
		return g.generateQueryHook(service, method, queryAnn)
	} else if mutationAnn != nil {
		return g.generateMutationHook(service, method, mutationAnn)
	} else if subscriptionAnn != nil {
		return g.generateSubscriptionHook(service, method, subscriptionAnn)
	} else {
		return g.generateBasicHook(service, method)
	}
}

// generateQueryHook generates a React Query query hook
func (g *Generator) generateQueryHook(service Service, method Method, ann *QueryAnnotation) (string, error) {
	tmpl := template.Must(template.New("query").Funcs(g.templateFuncs()).Parse(queryHookTemplate))

	data := map[string]interface{}{
		"ServiceName": service.Name,
		"MethodName":  method.Name,
		"HookName":    fmt.Sprintf("use%s", method.Name),
		"Params":      g.formatHookParams(method.Params),
		"ParamNames":  g.formatParamNames(method.Params),
		"QueryKey":    g.generateQueryKey(service.Name, method.Name, method.Params),
		"ReturnType":  g.formatReturns(method.Results),
		"Annotation":  ann,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateMutationHook generates a React Query mutation hook
func (g *Generator) generateMutationHook(service Service, method Method, ann *MutationAnnotation) (string, error) {
	tmpl := template.Must(template.New("mutation").Funcs(g.templateFuncs()).Parse(mutationHookTemplate))

	data := map[string]interface{}{
		"ServiceName":        service.Name,
		"MethodName":         method.Name,
		"HookName":           fmt.Sprintf("use%s", method.Name),
		"Params":             g.formatHookParams(method.Params),
		"ParamNames":         g.formatParamNames(method.Params),
		"ReturnType":         g.formatReturns(method.Results),
		"Annotation":         ann,
		"InvalidateQueries":  g.formatInvalidateQueries(ann.Invalidate),
		"OptimisticKey":      g.generateOptimisticKey(service.Name, method.Name),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateSubscriptionHook generates a subscription hook
func (g *Generator) generateSubscriptionHook(service Service, method Method, ann *SubscriptionAnnotation) (string, error) {
	tmpl := template.Must(template.New("subscription").Funcs(g.templateFuncs()).Parse(subscriptionHookTemplate))

	data := map[string]interface{}{
		"ServiceName": service.Name,
		"MethodName":  method.Name,
		"HookName":    fmt.Sprintf("use%s", method.Name),
		"ReturnType":  g.formatReturns(method.Results),
		"Annotation":  ann,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateBasicHook generates a basic hook without special annotations
func (g *Generator) generateBasicHook(service Service, method Method) (string, error) {
	tmpl := template.Must(template.New("basic").Funcs(g.templateFuncs()).Parse(basicHookTemplate))

	data := map[string]interface{}{
		"ServiceName": service.Name,
		"MethodName":  method.Name,
		"HookName":    fmt.Sprintf("use%s", method.Name),
		"Params":      g.formatHookParams(method.Params),
		"ParamNames":  g.formatParamNames(method.Params),
		"ReturnType":  g.formatReturns(method.Results),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateZodSchemas generates Zod validation schemas
func (g *Generator) generateZodSchemas(types []Type) (*plugins.GeneratedFile, error) {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Wails WRF plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")
	buf.WriteString("import { z } from 'zod';\n\n")

	for _, typ := range types {
		buf.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", typ.Name))

		for _, field := range typ.Fields {
			zodType := g.goTypeToZod(field.Type)
			validation := g.extractValidation(field)
			optional := g.isFieldOptional(field)

			fieldName := g.fieldNameToTS(field.Name)

			if optional {
				buf.WriteString(fmt.Sprintf("  %s: %s.optional()%s,\n", fieldName, zodType, validation))
			} else {
				buf.WriteString(fmt.Sprintf("  %s: %s%s,\n", fieldName, zodType, validation))
			}
		}

		buf.WriteString("});\n\n")
		buf.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %sSchema>;\n\n", typ.Name, typ.Name))
	}

	schemaPath := strings.Replace(g.config.Generation.Types.Output, ".ts", "-schemas.ts", 1)
	return &plugins.GeneratedFile{
		Path:      schemaPath,
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}, nil
}

// generateEventTypeDefinitions generates event type definitions
func (g *Generator) generateEventTypeDefinitions(services []Service) (*plugins.GeneratedFile, error) {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Wails WRF plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	// Generate event type map
	buf.WriteString("export interface WailsEventMap {\n")

	for _, service := range services {
		for _, method := range service.Methods {
			eventAnn := ExtractEventAnnotation(method.Annotations)
			if eventAnn != nil && eventAnn.EventName != "" {
				eventType := g.formatReturns(method.Results)
				buf.WriteString(fmt.Sprintf("  '%s': %s;\n", eventAnn.EventName, eventType))
			}
		}
	}

	buf.WriteString("}\n\n")

	// Generate typed event functions
	buf.WriteString("import { EventsOn, EventsOff, EventsEmit } from '@wailsjs/runtime/runtime';\n\n")
	buf.WriteString("export function TypedEventsOn<K extends keyof WailsEventMap>(\n")
	buf.WriteString("  eventName: K,\n")
	buf.WriteString("  callback: (data: WailsEventMap[K]) => void\n")
	buf.WriteString("): () => void {\n")
	buf.WriteString("  return EventsOn(eventName as string, callback);\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export function TypedEventsEmit<K extends keyof WailsEventMap>(\n")
	buf.WriteString("  eventName: K,\n")
	buf.WriteString("  data: WailsEventMap[K]\n")
	buf.WriteString("): void {\n")
	buf.WriteString("  EventsEmit(eventName as string, data);\n")
	buf.WriteString("}\n")

	return &plugins.GeneratedFile{
		Path:      g.config.Generation.Events.Output,
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}, nil
}

// generateHooksIndex generates index file for hooks
func (g *Generator) generateHooksIndex(services []Service) *plugins.GeneratedFile {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Wails WRF plugin\n")
	buf.WriteString("// DO NOT EDIT - This file is automatically generated\n\n")

	for _, service := range services {
		buf.WriteString(fmt.Sprintf("export * from './%sHooks';\n", service.Name))
	}

	return &plugins.GeneratedFile{
		Path:      fmt.Sprintf("%s/index.ts", g.config.Generation.Hooks.Output),
		Content:   buf.Bytes(),
		Mode:      0644,
		Overwrite: true,
	}
}

// Helper methods continue in next part due to length...